name: 'rust-clippy-check'
description: 'Run clippy and annotate the diff with errors and warnings'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black

inputs:
  token:
    description: GitHub token
    required: true
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  use-cross:
    description: Use cross instead of cargo
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
